src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h, src/d3d9/d3d9_state.h, src/dxso/dxso_compiler.cpp, src/dxso/dxso_compiler.h
Implements clipping planes in vertex shaders so that `clipDist = dot(clipPlane, vertexPos)`. This fixes some broken water reflections in Half-Life 2.
The first three patches are minor fixes around uniform buffers.
=> Implement clip planes

src/d3d11/d3d11_blend.cpp, src/d3d11/d3d11_swapchain.cpp, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h, src/d3d9/d3d9_presenter.cpp, src/d3d9/d3d9_state.h, src/dxso/dxso_compiler.cpp, src/dxso/dxso_compiler.h, src/dxso/dxso_util.cpp, src/dxso/dxso_util.h, src/dxvk/dxvk_constant_state.h, src/dxvk/dxvk_context.cpp, src/dxvk/dxvk_context.h, src/dxvk/dxvk_graphics.cpp, src/dxvk/dxvk_graphics.h, src/dxvk/dxvk_shader.h, src/dxvk/dxvk_spec_const.cpp, src/dxvk/dxvk_spec_const.h
See title. Uses specialization constants to select the alpha compare op in the fragment shader, and passes in the alpha reference using a uniform buffer.
Some backend work was done to expose the alpha compare op to the shader without breaking existing D3D11 state caches, I'll cherry-pick that commit into mainline DXVK should you decide to merge this implementation.
=> Implement Alpha Test

src/d3d9/d3d9_device.cpp
Prevents log file growing by dozens Kb/s in some cases.
Similar to https://github.com/doitsujin/dxvk/commit/c804d99db7db110228e4f233f079c7dac377e5d7
I used the most active functions I've found in log files, but you may want to apply similar changes to the rest stubs.
=> [d3d9] Reduce log spam in some stubs

dxvk.conf, src/d3d9/d3d9_swapchain.cpp
Currently `d3d9.presentInterval` option ignored.
With this fix everithing work as expected, e.g. `d3d9.presentInterval = 0` means vsync off, and `d3d9.presentInterval = 2` means "vsync / 2"
Fixes #89
=> [d3d9] Fix d3d9.presentInterval option behaviour

src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_options.cpp, src/d3d9/d3d9_options.h, src/util/config/config.cpp
Risen 1 copies data to buffers that were locked as readonly and expects that to work. Because of this most of the game isn't renderer because the vertex/index data never gets copied to the gpu.
I decided to add a config option and allow readonly locking by default to avoid unnecessary copies in other games. Let's see if we find more games that are broken like this.
=> Add an option to disable read only locking

src/d3d9/d3d9_state.h
With D3D9 you can apparently set render states up to the type 255.
I forgot to resize the array in my pr yesterday.
=> [d3d9] Extend RenderStateCount to 256

src/d3d9/d3d9_constant_set.h, src/d3d9/d3d9_device.cpp, src/dxso/dxso_compiler.cpp, src/dxso/dxso_isgn.h
Improves performance in Dragon Age Origins by ~10%.
This does **not** perform any sort of compaction just yet. Implementing that would require an analysis pass in the shader compiler that figures out whether relative indexing is used, which might be quite tricky to do.
=> Optimize shader constant updates

src/util/config/config.cpp
Risen 2 and 3 suffer from the same issue as Risen 1.
=> [util] Disable readonly locking for Risen 2 & 3

src/d3d9/d3d9_stateblock.h
Fixes the loading screen in Guild 2 when D9VK gets compiled with MSVC.
~~Might also fix the main menu with the constant opt branch.~~
Also fixes the main menu issues with the constant-opt branch according to Riesi.
=> Properly initialize state block

src/d3d9/d3d9_device.cpp
Closes #203 
Fixes a crash in Torchlight. The game doesn't render correctly (probably because of unimplemented fixed function stuff) but at least it doesn't crash anymore.
=> [d3d9] Correct highest texture stage type

src/d3d9/d3d9_texture.cpp
Fixes #208
(Hopefully)
Just checking the subresource isn't sufficient because it would just return the first mip level of the next face.
=> [d3d9] Properly check mip level for cube map surfaces

src/d3d9/d3d9_common_texture.cpp, src/d3d9/d3d9_common_texture.h, src/d3d9/d3d9_device.cpp
Fixes an issue with discarding managed textures
=> [d3d9] Store the mapped slice

src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h, src/dxvk/dxvk_buffer.h
The previous implementation had one major issue: If a game calls `DrawPrimitiveUP` once with a large number of vertices and then submits many draw calls with a small vertex count, we'd allocate one large buffer slice on each draw call.
This new implementation copies all vertex and index data into one 4MB slice until it is full, resulting in a lower memory footprint. For more than 4MB of data, a temporary buffer is allocated, but this should hopefully never happen in practice.
=> [d3d9] Improve AllocUpBuffer behaviour to waste less memory

src/d3d9/d3d9_device.cpp
While it is usually a good idea to use `DEVICE_LOCAL | HOST_VISIBLE` memory for uniform buffers, it doesn't really seem to work all that well in D3D9 workloads and heavily tanks CPU-bound performance for some reason.
This improves CPU-bound performance in The Witcher 2 by ~25%; GPU-bound perf takes a negligible hit (~1% or so, probably within error margins).
I'm not entirely sure *why* the performance hit is this dramatic, but one reason might be that for shaders with dynamic indexing, we have to always upload the entire buffer, which usually leads to a **lot** of data being written but never read.
This won't have any effect at all on systems with Nvidia GPUs since they don't expose host-visible device memory.
=> [d3d9] Don't use DEVICE_LOCAL memory for shader constant buffers

src/d3d9/d3d9_device.cpp
Fixes #247 
You can use sysmem textures as the source for copy operations and we should avoid rewriting the texture data while a copy is happening.
=> [d3d9] Properly wait for texture mapping buffers

src/d3d9/d3d9_device.cpp
=> [d3d9] Ignore lock flag DISCARD when NOOVERWRITE is also specified

src/dxvk/dxvk_image.h
Should fix a silly compiler warning and improves code gen, which
is important since this is *the* most frequently called function
in the backend.
=> [dxvk] Improve DxvkImageView::handle()

src/d3d9/d3d9_device.cpp
Basically, instead of walking over all 21 samplers every time
and checking whether they are dirty, just iterate over the
dirty bits.
=> [d3d9] Optimize UndirtySamplers

src/d3d9/d3d9_device.cpp
This hasn't caused any issues yet but there are probably games out there that will break if we don't check it correctly.
=> [d3d9] Check texture usage in SetRT and SetDS

src/util/util_bit.h
=> [util] Fix use of lzcnt intrinsic in GCC

src/d3d9/d3d9_shader.cpp, src/dxso/dxso_common.h
Witcher 2 tries to create vertex shaders with pixel shader bytecode. D3D9 and WineD3D both fail with INVALID_CALL. D9VK currently allows that and returns D3D_OK.
This PR fixes that.
=> Check bytecode type when creating shaders

src/d3d9/d3d9_device.cpp
Fixes #264 
Also fixes the MSAA crash in GTA SA.
```
/* all render targets must have the same size and the depth buffer must be
* bigger. Multisample has to match, according to spec. But some apps do
* things wrong there, and no error is returned. The behaviour they get
* apparently is that depth buffer is disabled if it doesn't match.
* Surely the same for render targets. */
```
https://github.com/mesa3d/mesa/blob/ce57f4f7c4d672a88527d0d346e27b902cfc3c6a/src/gallium/state_trackers/nine/nine_state.c#L705
=> Unbind DS and RTs if sample counts or sizes dont match

src/d3d9/d3d9_adapter.cpp, src/d3d9/d3d9_options.cpp, src/d3d9/d3d9_options.h, src/util/config/config.cpp
Fixes #268 
We've talked about this on Discord. I think this is the lesser evil compared to adding a hack to ignore 1x1 RTs.
=> Disable the DF24 format for Dead Space

src/d3d9/d3d9_device.cpp
=> [d3d9] Remove DS size log message

src/d3d9/d3d9_fixed_function.cpp
This fixes a rendering issue in fr-030 candytron.
=> [d3d9] Ensure normalize(vec3(0.0)) returns 0.0 instead of NaN.

src/dxso/dxso_compiler.cpp, src/dxso/dxso_compiler.h
This series refactors constant loading to not rely on `getOperandPtr`, similar to what has already been done for D3D11, and implements range checking on top of that. This should hopefully fix a number of issues related to out-of-bounds constant access on Nvidia GPUs.
=> [dxso] Implement constant range check for relative indexing

src/d3d9/d3d9_main.cpp
Everything defined in d3d9_include.h
This should silence annoying warning during compilation.
=> [d3d9] Remove unneeded include

src/d3d9/d3d9_include.h
Required for -fvisibility=hidden compiler flag (winelib compilation).
=> [d3d9] Sync DLLEXPORT definition with DXVK

src/util/config/config.cpp
The current default value is definitely too high. I am able to reproduce a crash by simply trying to edit a community lot after entering Belladonna Cove on my RTX 2080 on Windows 10. Setting a lower value fixes the crashes and allows the game to be playable. Also, a high value prevents higher resolutions from loading to the neighborhood screen for some reason. 
Lower values than 2GB can definitely be used as well. The Sims 2 was developed in an era where high-end graphics cards topped out around 768MB. If there are further reports of crashes, advise future users to try lowering this value in `dxvk.conf` even more as a troubleshooting step. 
I don't think users will be clamoring to keep this value high though. Users who are looking to push graphical limits/fantasies in their Sims should …
=> [util] Report 2GB vram max for The Sims 2

src/util/config/config.cpp
Maybe we should consider changing the flag readonly to opt-in rather than opt-out.
=> [util] Disable read only locking for Burnout Paradise

src/meson.build
Fixes the build when both `enable_d3d10` and `enable_d3d11` are set to false.
```
src/meson.build:8:4: ERROR: Problem encountered: D3D10 and/or D3D11 required for DXGI to properly functionning.
```
Also see https://github.com/Joshua-Ashton/d9vk/issues/398.
=> meson: Check if d3d9 is enabled too.

src/util/config/config.cpp
Based on the default config, and gamecode this is the best option for this game as it avoids workarounds that were specifically designed for old GPUs that on modern day hardware and in d9vk break rendering. (tested on multiple sets of hardware and software configurations).
The vendor is set to AMD as:
- It enables a few AMD specific decal layering fixes that are needed on all hardware.
- It avoids certain invalid rendering methods.
- It avoids the game's rendering being affected when it detects Intel graphics hardware.
- It avoids a sometimes confusing error on startup.
- It avoids the need of common text file tweaks while not breaking configurations that were tweaked this way.
The game has a lot of hardware specific workarounds that can cause random compatibility issues with d9vk. This …
=> [util] Force vendorId and deviceId for Halo CE

src/util/config/config.cpp
The one time I don't check stuff I break something on a colossal level. I got cocky.
That is valid syntax in like only one flavor of regex.
I'm embarrassed of myself.
=> [util] Fix broken regex in config.cpp

src/d3d9/d3d9_fixed_function.cpp
This fixes a rendering issue in virtual vodka by fairlight.
=> [d3d9] NMin the ffp light attenuation
